### ISSUE TITLE
Curious about pub/priv SSH keys in /etc/ssh in current jenkins/ssh-agent:jdk11

### ISSUE THREAD

**Issue by isuftin** [jenkinsci/docker-ssh-agent#116]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Trivy just flagged these private key files as secrets and until now I didn't know they were in here. What is the purpose of these? 

```
root@65660bb4c656:/etc/ssh# ls -al *key*
-rw------- 1 root root  513 Apr 27 02:07 ssh_host_ecdsa_key
-rw-r--r-- 1 root root  182 Apr 27 02:07 ssh_host_ecdsa_key.pub
-rw------- 1 root root  411 Apr 27 02:07 ssh_host_ed25519_key
-rw-r--r-- 1 root root  102 Apr 27 02:07 ssh_host_ed25519_key.pub
-rw------- 1 root root 2610 Apr 27 02:07 ssh_host_rsa_key
-rw-r--r-- 1 root root  574 Apr 27 02:07 ssh_host_rsa_key.pub

cat ssh_host_rsa_key.pub
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDXf6Mau+UNRzXQ0YiLjDh9FuHnORh2quSqgqCGuh0ZpLJmshIHEMdg7xq1ZY/t8CzeGkREvv3acqOMS3J87SNGCnZM7D7++GjqOVnnXUqLv2JxMjTTUUpTB7ATMUCsSa4ZlF/UxBaz62iZEbvi0GM2k3U/GH28
UhMW7BtWUsKOZQ8JzDhiwa0pxF95WncM81sCBotSKcTmshb1PTQTbXMpweYn0+y849SmuQCp5LhxeO9xWjuutbqqwbpZWVRq1p/BbzN29O/cDYFnC//aPYsYzTHHFKxE9STkRuFLxf0Om7zjxzIvfg2LyYZ1bW6sXuL9PUyp9wnR4Xp0fQb7aM/PSxdktwFCDvgC
RJJO0IGxQzpUEQuCRC1ijU7Fqk1hQJXRFeuuiRxzG3zaEzpH/JCx389Xme40T1d9BogiI5qVlknTK7UkIj0WA3MyvguT1M4S3evaraL4UUfm38dK2/Nm6Ingm2EWTKU7eHszhVVF895bJ2M/azs4tlCVz2RkJBs= root@buildkitsandbox
```

```

### Reproduction steps


Reproduce:

```
docker run --rm -it  jenkins/ssh-agent:jdk11 cat /etc/ssh/ssh_host_rsa_key.pub
Unable to find image 'jenkins/ssh-agent:jdk11' locally
jdk11: Pulling from jenkins/ssh-agent
Digest: sha256:55097f121513fd49ec7e065c0500c480cbacbd818ee91be8804d5c80e75ac0ac
Status: Downloaded newer image for jenkins/ssh-agent:jdk11
+ [[ '' == ssh-* ]]
+ [[ '' == ssh-* ]]
+ env
+ grep _
+ [[ 2 -gt 0 ]]
+ echo 'setup-sshd params: cat' /etc/ssh/ssh_host_rsa_key.pub
setup-sshd params: cat /etc/ssh/ssh_host_rsa_key.pub
+ [[ cat == ssh-* ]]
+ [[ cat /etc/ssh/ssh_host_rsa_key.pub == \/\u\s\r\/\s\b\i\n\/\s\s\h\d\ \-\D\ \-\p\ \2\2 ]]
+ echo 'Executing params: '\''cat' '/etc/ssh/ssh_host_rsa_key.pub'\'''
Executing params: 'cat /etc/ssh/ssh_host_rsa_key.pub'
+ exec cat /etc/ssh/ssh_host_rsa_key.pub
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDXf6Mau+UNRzXQ0YiLjDh9FuHnORh2quSqgqCGuh0ZpLJmshIHEMdg7xq1ZY/t8CzeGkREvv3acqOMS3J87SNGCnZM7D7++GjqOVnnXUqLv2JxMjTTUUpTB7ATMUCsSa4ZlF/UxBaz62iZEbvi0GM2k3U/GH28
UhMW7BtWUsKOZQ8JzDhiwa0pxF95WncM81sCBotSKcTmshb1PTQTbXMpweYn0+y849SmuQCp5LhxeO9xWjuutbqqwbpZWVRq1p/BbzN29O/cDYFnC//aPYsYzTHHFKxE9STkRuFLxf0Om7zjxzIvfg2LyYZ1bW6sXuL9PUyp9wnR4Xp0fQb7aM/PSxdktwFCDvgC
RJJO0IGxQzpUEQuCRC1ijU7Fqk1hQJXRFeuuiRxzG3zaEzpH/JCx389Xme40T1d9BogiI5qVlknTK7UkIj0WA3MyvguT1M4S3evaraL4UUfm38dK2/Nm6Ingm2EWTKU7eHszhVVF895bJ2M/azs4tlCVz2RkJBs= root@buildkitsandbox

### Expected Results

Was not expecting any pub/priv keys in /etc/ssh/

### Actual Results

pub/priv keys in /etc/ssh/

### Anything else?

Should these be removed? Do they hold some functionality for our use?

**Comment by MarkEWaite** [comment]
The `/etc/ssh/ssh_host_*` files are the ssh host keys for the Docker image that has been built.  See the ["Explaining ssh host keys"](https://www.ssh.com/academy/ssh/host-key) for more details about the uses of ssh host keys.

**Comment by isuftin** [comment]
@MarkEWaite  - Understood. So it seems like this is an artifact of the image build. When building a derivative image using this image as the base, I'm assuming it's fine to remove these keys as they only would pertain to the initial build?

**Comment by MarkEWaite** [comment]
> @MarkEWaite - Understood. So it seems like this is an artifact of the image build. When building a derivative image using this image as the base, I'm assuming it's fine to remove these keys as they only would pertain to the initial build?

If the derivative image works for you without those files, you're welcome to remove them.  I haven't tried removing those files in a derivative image.

**Comment by isuftin** [comment]
@MarkEWaite  - Thanks for the information.
