### ISSUE TITLE
problem with docker pipelines because of shared volume /tmp /run /var/run

### ISSUE THREAD

**Issue by alexeygrigorovaurea** [jenkinsci/docker-ssh-agent#18]
Hi there
there is a problem i caught , when I'm using docker pipeline with parallel step and agent is running from this image.
I'm using parallel where in each branch I'm spinning a docker container and run some suite in each container. Because docker-workflow plugin automatically use --volumes-from, all of those containers  have /tmp , /var/run and /run mounted between each other. And  that test suite works unpredictably because same files/sockets accessed from different containers.

Is there any reason to have those dirs marked as a volume or it can be considered as a bug?

**Comment by slfotg** [comment]
I was just looking at this and trying to figure out why those three directories are marked as volumes as well.

**Comment by joastoe** [comment]
I face the same issue and it gives me a lot of troubles. Furthermore, the $JENKINS_HOME directory is now also mounted as a volume and covers all files additionally added there.
What's the purpose of those mounts? I'd like to see them removed.

**Comment by timja** [comment]
Avoid the docker workflow plugin where you can.

It does some _creative_ things.

Just use `docker run` directly
