### ISSUE TITLE
Deprecate JDK8 images

### ISSUE THREAD

**Issue by dduportal** [jenkinsci/docker-ssh-agent#210]
Jenkins [requires Java 11](https://www.jenkins.io/blog/2022/06/28/require-java-11/) since June 2022 for the weekly release line and September 2022 for LTS release line.

For the jenkinsci/docker-agent and jenkinsci/docker-inbound-agent, a last release had been delivered a few month ago with the latest remoting `agent.jar` compatible with JDK8 (ref. https://github.com/jenkinsci/docker-agent/issues/298).

For the SSH agent image here, there is no requirement around the `agent.jar` because it is not part of the image.
However it does not make sense to ship JDK8 version anymore. 

Proposal: we should deprecate JDK8 SSH agent images (and associated tooling such as dependabot) in a new `5.x.y` release line (current release is `4.10.0`) on the principal branch.

The only "danger" is to be careful to properly write the changelog (either with good PR title and labelling to hint release-drafter, or even when publishing the release).

Ping @poddingue @MarkEWaite @timja @NotMyFault @basil @halkeye @jglick @imonteroperez do you see any potential problem for this?

**Comment by timja** [comment]
no issues with it

**Comment by NotMyFault** [comment]
I'm fine with that proposal.

**Comment by dduportal** [comment]
- Implemented in https://github.com/jenkinsci/docker-ssh-agent/pull/238
- Last release with JDK8: https://github.com/jenkinsci/docker-ssh-agent/releases/tag/4.16.0
- First release with only JDK11 and JDK17 for lInux (and only JDK11 for Windows): https://github.com/jenkinsci/docker-ssh-agent/releases/tag/5.0.0
