### ISSUE TITLE
Track JDK versions with `updatecli`

### ISSUE THREAD

**Issue by dduportal** [jenkinsci/docker-ssh-agent#242]
JDK versions are either passed as build argument to Dockerfiles, as Docker Bakefile variable or powershell tooling.

We should track the JDK version like in jenkinsci/docker-agent and jenkinsci/docker-inbound-agent (example: https://github.com/jenkinsci/docker-agent/blob/master/updatecli/updatecli.d/jdk11.yaml) to avoid manual PRs.

**Comment by lemeurherve** [comment]
Done in https://github.com/jenkinsci/docker-ssh-agent/pull/256
