### ISSUE TITLE
 Add support for Windows LTS 2022 Images

### ISSUE THREAD

**Issue by dduportal** [jenkinsci/docker-ssh-agent#245]
### What feature do you want to see added?

Same as https://github.com/jenkinsci/docker-agent/issues/424

**Comment by lemeurherve** [comment]
Addressed in #385, corresponding release: https://github.com/jenkinsci/docker-ssh-agent/releases/tag/5.30.0

**Comment by dduportal** [comment]
Available since the 5.30.0 release: https://hub.docker.com/r/jenkins/ssh-agent/tags?page=1&name=2022


👏
