### ISSUE TITLE
maven-surefire-could-not-find-forkedbooter-class

### ISSUE THREAD

**Issue by alxayo** [jenkinsci/docker-ssh-agent#31]
Seems the container uses 
- openjdk version "1.8.0_181"
- OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-2~deb9u1-b13)

and when used with MAVEN results in issues decried here:
- https://stackoverflow.com/questions/53010200/maven-surefire-could-not-find-forkedbooter-class
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911925
- https://issues.apache.org/jira/browse/SUREFIRE-1588?focusedCommentId=16671777&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16671777 

FROM

**Comment by timja** [comment]
We're currently using `openjdk version "1.8.0_302"`
