### ISSUE TITLE
Add GA JDK21 Alpine-based arm64 images

### ISSUE THREAD

**Issue by marvinruder** [jenkinsci/docker-ssh-agent#346]
### What feature do you want to see added?

I would like to have a non-`preview` image based on Alpine Linux for arm64 architecture. This is now possible as base images of this type with JDK21 are now generally available from Eclipse Temurin.

### Upstream changes

The base image (Eclipse Temurin JDK21) was tracked in https://github.com/adoptium/containers/issues/158.
The main Jenkins image did the same change already, tracked in https://github.com/jenkinsci/docker/issues/1244.

**Comment by gounthar** [comment]
For JDK21, we don't use the Temurin image as a base. Instead, we begin with a base OS image and then directly download the Temurin binary.

However, we have noticed some inconsistency between different platforms.

In the [latest GA release](https://github.com/adoptium/temurin21-binaries/releases/tag/jdk-21.0.1%2B12), you'll find binaries for `aarch64`, `amd64`, `ppc64le`, `Windows`, and `macOS`, but no `arm32 `or `s390x`. Versions for these two platforms are available in [early access releases](https://github.com/adoptium/temurin21-binaries/releases/tag/jdk-21.0.1%2B12-ea-beta).

This won't be a simple find/replace in the [Docker bake file](https://github.com/jenkinsci/docker-ssh-agent/blob/master/docker-bake.hcl#L178). I believe we'll need to split the effort into two parts, maintaining the preview for non-GA platforms.

Are you interested in contributing? You can use what has already been done in other repositories of this organization as a guide.

**Comment by marvinruder** [comment]
> Are you interested in contributing? You can use [what has already been done](https://github.com/jenkinsci/docker-agent/blob/master/docker-bake.hcl#L214) in other repositories of this organization as a guide.

Will definitely try when I find the time!

**Comment by marvinruder** [comment]
> In the [latest GA release](https://github.com/adoptium/temurin21-binaries/releases/tag/jdk-21.0.1%2B12), you'll find binaries for `aarch64`, `amd64`, `ppc64le`, `Windows`, and `macOS`, but no `arm32 `or `s390x`. Versions for these two platforms are available in [early access releases](https://github.com/adoptium/temurin21-binaries/releases/tag/jdk-21.0.1%2B12-ea-beta).

It would appear that all architectures for which Alpine early access builds exist are already in GA and have their own base images, so there should be no need for Alpine `preview` builds anymore.
