### ISSUE TITLE
The list of JDK to build is duplicated in docker-bake.hcl

### ISSUE THREAD

**Issue by lemeurherve** [jenkinsci/docker-ssh-agent#418]
### Jenkins and plugins versions report

N/A

### What Operating System are you using (both controller, and any agents involved in the problem)?

N/A

### Reproduction steps

1. Notice that the list of JDK to build is duplicated in docker-bake.hcl

### Expected Results

The list is defined at a single place to avoid mistakes or oversights when updating it.

### Actual Results

The list is duplicated.

### Are you interested in contributing a fix?

Yes:
- #419

**Comment by dduportal** [comment]
Removing the `bug` label in favor of `chore` (as the artifacts are not impacted). But this is a legit request!

**Comment by dduportal** [comment]
Closed by https://github.com/jenkinsci/docker-ssh-agent/pull/419
