### ISSUE TITLE
Update docker-ssh-agent README.md

### ISSUE THREAD

**Issue by ajurry** [jenkinsci/docker-ssh-agent#57]
Currently, the docker-ssh-agent README.md contains tags that don't seem to be supported.

Tags that are currently supported are: **latest, alpine, jdk11 and latest-jdk11**

Tags that seem like they're no longer supported are: **jdk8-windowsservercore-1809, jdk11-windowsservercore-1809, jdk8-nanoserver-1809 and jdk11-nanoserver-1809**

**Comment by ajurry** [comment]
It could also be possible that the windowsservercore and nanoserver are not working, as the most recent commits seem to state that certain Windows tags have been updated. Either way, something seems to give a bad whiff :)

**Comment by hutson** [comment]
According to the Windows Image blog (https://www.jenkins.io/blog/2020/05/11/docker-windows-agents/), there should be an image tag called `jdk8-windowsservercore-1809`. However, the `ssh-agent` repository uses `windowsservercore-1809-jdk8`. Therefore there's inconsistency between what is documented and what is actually available.

**Comment by tougemasta** [comment]
Has this project been abandoned?

**Comment by timja** [comment]
> Has this project been abandoned?

I'm refreshing the docker images currently but yes they've suffered from a lack of an active maintainer (which I can't commit to but I'll try fix some of the current issues and clear PR backlogs now)
