### ISSUE TITLE
How to set-up with Jenkins Docker plugin

### ISSUE THREAD

**Issue by dgokcin** [jenkinsci/docker-ssh-agent#64]
Hello

I would like to use the jenkins/ssh-agent:windowsservercore-1809 ssh agent docker image in the Jenkins Docker Pkugin to fire windows build agents, build & test and destroy the image. I am confused on using the JENKINS_AGENT_SSH_PUBKEY. Where is my SSH public key. Are we talking about the public key on the Jenkins Master node or the agent which has the Docker Deamon running for windows containers? Could you please help me to set this up?

Thanks!!

**Comment by MarkEWaite** [comment]
The issue tracker for the docker-ssh-agent is used to track issues.  Your request seems to be a request for help, not a report of a documentation issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions.
