### ISSUE TITLE
Failed to install packages, like git

### ISSUE THREAD

**Issue by yang-ling** [jenkinsci/docker-ssh-agent#96]
I've created a Dockerfile:

``` dockerfile
FROM jenkins/ssh-agent:jdk11

RUN apt-get install --no-install-recommends -y git
```

But when I build it, it failed to install git. Error messages are:

```
Step 3/3 : RUN apt-get install --no-install-recommends -y git
 ---> Running in f22329c700a5
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package git
The command '/bin/sh -c apt-get install --no-install-recommends -y git' returned a non-zero code: 100
ERROR: Service 'agent1' failed to build
```

I checked Dockerfile of `jenkins/ssh-agent:jdk11`, and found this line: https://github.com/jenkinsci/docker-ssh-agent/blob/7bdef2e63ef137a429a109c380f54ec51d1f0992/11/bullseye/Dockerfile#L49

`rm -rf /var/lib/apt/lists/*` it removes all source lists. That's why my Dockerfile failed to install git.

I want to know is it on purpose?
If so, then what is the recommended way to install packages on this agent image?

Thanks in advance!

**Comment by MarkEWaite** [comment]
Thanks for including the line that inspired the question.

Command line git is already installed in the Docker image `jenkins/ssh-agent:jdk11`.  I confirmed that with the command:

```
$ docker run --rm -i -t jenkins/ssh-agent:jdk11 git --version
...
git version 2.30.2
```

However, if you need to install some other program, then you'll need to become the root user in the Dockerfile and perform the apt-get commands to perform the installation.  Something like this:

```
FROM jenkins/ssh-agent:jdk11

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
  gnupg \
  make \
  procps \
  wget \
  && rm -rf /var/lib/apt/lists/*

USER jenkins
```

For future reference, you may be able to find these types of answers in the history of the line in question.  In the view to the left of that line on GitHub, there are three horizontal dots.  When you click those dots, it shows a pop-up menu that includes "View git blame".  When you click "View git blame" it opens an annotated view of the file with the commit for that line.  That line was [committed 4 years ago](https://github.com/jenkinsci/docker-ssh-agent/commit/935b02dc9ac38a825fe2cf52a25bb7cfe2b61856) and has the message:

> Dockerfile: Clean apt cache properly
>
> As per Docker's best practices guide [1], `apt-get clean` doesn't remove all of apt's cache: the directories under `/var/lib/apt/lists` must be deleted. This commit therefore amends the `apt-get` command to delete these cache files after installing packages; the `clean` command is no longer necessary.
> 
> [1]: https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#run
