### ISSUE TITLE
Add building instructions

### ISSUE THREAD

**Issue by OLEGSHA** [jenkinsci/docker-ssh-agent#97]
### Describe your use-case which is not covered by existing documentation.

It seems that the repository is set up to be built by the maintainers. However, some users, myself included, may want to build modified versions on the docker image. There are currently no indications on how images might be built manually, and there is no dependency management for building. It would benefit the inexperienced users greatly to document the build command(s) and the tools and dependencies required.

From what I've seen digging around the repository, one should have `buildx` plugin for Docker, have `jq` in PATH, and use `make build` to build a Linux image.

**Comment by gounthar** [comment]
Good idea 👍 
Let me make a proposal for this. 👀

**Comment by gounthar** [comment]
I made the first draft there: #189 .

**Comment by gounthar** [comment]
@OLEGSHA does the current documentation suit you?
Can we close the issue?

**Comment by OLEGSHA** [comment]
Yes, this is exactly what I meant. Thank you so much!

**Comment by gounthar** [comment]
Thanks for opening this issue and for your feedback.
